models:
  qr_model: "/Users/saieshagre/Downloads/NxtQube/UpdatedInventoryManagement/Requirement files/qr_detection.pt"
  blue_bar_model: "/Users/saieshagre/Downloads/InventoryManagement/Requirement files/blue_bar_detection.pt"
  box_model: "/Users/saieshagre/Downloads/InventoryManagement/Requirement files/box_detection.pt"
  orange_bar_model: "/Users/saieshagre/Downloads/InventoryManagement/Requirement files/orange_bar_detection.pt"

csv:
  nomenclature: "/Users/saieshagre/Downloads/InventoryManagement/Requirement files/rack structure.csv"
  row_data: "/Users/saieshagre/Downloads/InventoryManagement/Requirement files/row-data (14).csv"

input:
  image_directory: "/Users/saieshagre/Downloads/InventoryManagement/temp_images"
