models:
  qr_model: "./models/qr_detection.pt"
  blue_bar_model: "./models/blue_bar_detection.pt"
  pallet_model: "./models/pallet1.pt"
  orange_bar_model: "./models/orange_bar_detection.pt"

csv:
  nomenclature: "./models/rack structure.csv"
  row_data: "./models/row-data (14).csv"

input:
  image_directory: "./test images"

thresholds:
  blue_bar_model:
    confidence_threshold: 0.5
    merge_threshold: 50
  
  orange_bar_model:
    confidence_threshold: 0.5
